"use client";

import React from "react";
import { useTranslation } from "react-i18next";

interface VerifiedBadgeProps {
  isGrounded: boolean;
  chunksUsed?: number;
}

/**
 * Displays a verification badge indicating whether content is
 * RAG-grounded (verified from curriculum materials) or AI-generated.
 */
export default function VerifiedBadge({ isGrounded, chunksUsed }: VerifiedBadgeProps) {
  const { t } = useTranslation();

  if (isGrounded) {
    return (
      <span
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border-[2.5px] border-black bg-[#B6FF00] shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] text-xs font-extrabold uppercase tracking-widest"
        title={`Grounded in ${chunksUsed || 0} verified curriculum sources`}
      >
        <svg className="w-3.5 h-3.5" viewBox="0 0 20 20" fill="none">
          <path
            d="M10 2L12.09 7.26L18 8.27L14 12.14L14.81 18.02L10 15.27L5.19 18.02L6 12.14L2 8.27L7.91 7.26L10 2Z"
            fill="currentColor"
            stroke="black"
            strokeWidth="1.5"
          />
        </svg>
        {t("summaries.verified", "Verified")}
      </span>
    );
  }

  return (
    <span
      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border-[2.5px] border-black bg-white shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] text-xs font-extrabold uppercase tracking-widest text-stone-600"
      title="Generated by AI without curriculum grounding"
    >
      <svg className="w-3.5 h-3.5" viewBox="0 0 20 20" fill="none">
        <circle cx="10" cy="10" r="7" stroke="currentColor" strokeWidth="2" />
        <path d="M10 6V11" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        <circle cx="10" cy="14" r="1" fill="currentColor" />
      </svg>
      {t("summaries.aiGenerated", "AI-Generated")}
    </span>
  );
}
